[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://the-wild-oasis-website.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_qFUSX3kmfBbm7yoSZpLpKg_IQv9qUg9"